title: Super Squirrel
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
color_scheme: light
accent_color: pink
header:
  title: Super Squirrel
  has_nav: true
footer:
  content: 'ğŸ¿ï¸&copy; 2020. Super Squirrel. No cookies are used on this website.'
  # links:
  #   - text: Made with Stackbit
  #     url: 'https://www.stackbit.com'
  #     new_window: true
  has_social: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
